mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.study.hunting.domain
server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: userSystem
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.195.136:8848
        username: nacos
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.195.136:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root
    url: jdbc:mysql://localhost:3306/hunting_user?serverTimezone=UTC
    username: root
  session:
    store-type: redis
  redis:
    host: 192.168.195.136
    database: 0
    port: 6379
    timeout: 3600
    lettuce.pool.max-active: 16
    lettuce.pool.max-wait: -1ms
    lettuce.pool.max-idle: 8
    lettuce.pool.min-idle: 1

## 配置seata客户端的信息
#seata:
#  enabled: true
#  enable-auto-data-source-proxy: false
#  application-id: ${spring.application.name}
#  tx-service-group: my_tx_group
#  service:
#    vgroup-mapping:
#      my_tx_group: default
#  # 不使用注册中心和配置中心不加以下配置
#  config:
#    type: nacos
#    nacos:
#      server-addr: 192.168.195.136:8848
#      group: "SEATA_GROUP"
#      namespace: "seata"
#      dataId: "seataServer.properties"
#      username: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 192.168.195.136:8848
#      group: "SEATA_GROUP"
#      namespace: "seata"
#      username: "nacos"
#      password: "nacos"

management:
  endpoint:
    web:
      exposure:
        include:'*'

